version: "3.9"
services:
  tf-eks-repo-template:
    volumes:
      - vscode-extensions:/root/.vscode-server/extensions
      - vscode-extensions-insiders:/root/.vscode-server-insiders/extensions
      - ~/.config/gh:/terratest/.config/gh:ro
      - ~/.kube:/terratest/.kube
      - ~/.aws/credentials:/terratest/.aws/credentials:ro
      - go:/go
    command: /bin/sh -c "while sleep 1000; do :; done"

volumes:
  vscode-extensions:
    name: tf-eks-repo-template-vscode-extensions
  vscode-extensions-insiders:
    name: tf-eks-repo-template-vscode-extensions-insiders
  go:
    name: tf-eks-repo-template-go
