version: "3.9"

services:
  tf-eks-repo-template:
    container_name: tf-eks-repo-template
    image: utkusarioglu/tf-eks-devcontainer:1.2.15
    environment:
      TZ: Etc/UTC0
    extra_hosts:
      tf-eks-repo-template.templates.utkusarioglu.com: host-gateway
    volumes:
      - type: bind
        source: ..
        target: /utkusarioglu-com/templates/tf-eks-repo-template
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
